name: "Publish to PyPi"
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and publish to PyPi
        uses: JRubrics/poetry-publish@v1.15
        with:
          python_version: "3.10.8"
          poetry_version: "==1.3.1"
          pypi_token: ${{ secrets.PYPI_TOKEN }}
          build_format: "wheel"
          ignore_dev_requirements: "yes"
